const express = require("express");
const cors = require("cors");
const path = require("path");

const app = express();
const PORT = process.env.PORT || 10000;

app.use(cors()); // Enable CORS
app.use(express.static("public")); // Serve static files (HTML, CSS, JS)

const searchData = [
  { title: "Example Domain", url: "https://example.com", description: "This is an example website." },
  { title: "Python Official", url: "https://www.python.org", description: "Python is a programming language." },
  { title: "Flask Framework", url: "https://flask.palletsprojects.com", description: "Flask is a web framework for Python." },
  { title: "Amazon", url: "https://www.amazon.com/", description: "Amazon is a shopping website with various products." },
  { title: "Apple", url: "https://www.apple.com", description: "Official site for Apple products." },
  { title: "Google", url: "https://www.google.com", description: "The world's most popular search engine." },
  { title: "YouTube", url: "https://www.youtube.com", description: "A video-sharing platform with millions of videos." },
  { title: "Facebook", url: "https://www.facebook.com", description: "A social networking site connecting people worldwide." },
  { title: "Twitter", url: "https://www.twitter.com", description: "A microblogging platform for short posts and updates." },
  { title: "LinkedIn", url: "https://www.linkedin.com", description: "A professional networking platform." },
  { title: "Wikipedia", url: "https://www.wikipedia.org", description: "A free online encyclopedia with millions of articles." },
  { title: "Reddit", url: "https://www.reddit.com", description: "A community-driven forum with discussions on various topics." },
  { title: "Netflix", url: "https://www.netflix.com", description: "A streaming service offering movies and TV shows." },
  { title: "GitHub", url: "https://www.github.com", description: "A platform for developers to share and collaborate on code." },
  { title: "Stack Overflow", url: "https://stackoverflow.com", description: "A Q&A site for programmers and developers." },
  { title: "BBC News", url: "https://www.bbc.com/news", description: "A global news organization providing the latest news." },
  { title: "CNN", url: "https://www.cnn.com", description: "A major news network covering international affairs." },
  { title: "Instagram", url: "https://www.instagram.com", description: "A social media platform for sharing photos and videos." },
  { title: "Microsoft", url: "https://www.microsoft.com", description: "A technology company known for Windows, Office, and more." },
  { "title": "Google", "url": "https://www.google.com", "description": "The world's most popular search engine." },
  { "title": "GitHub", "url": "https://www.github.com", "description": "A code-sharing platform for developers." },
  { "title": "Stack Overflow", "url": "https://stackoverflow.com", "description": "A Q&A site for programmers." },
  { "title": "Mozilla", "url": "https://www.mozilla.org", "description": "Creators of the Firefox web browser." },
  { "title": "Linux", "url": "https://www.linux.org", "description": "Open-source operating system information and downloads." },
  { "title": "OpenAI", "url": "https://www.openai.com", "description": "Artificial intelligence research and development." },
  { "title": "Adobe", "url": "https://www.adobe.com", "description": "Creative software for design and media." },
  { "title": "Microsoft", "url": "https://www.microsoft.com", "description": "Home of Windows, Office, and cloud services." },
  { "title": "Apple", "url": "https://www.apple.com", "description": "Official site for iPhones, MacBooks, and other Apple products." },
  { "title": "Intel", "url": "https://www.intel.com", "description": "Leading semiconductor and processor manufacturer." },
  { "title": "Facebook", "url": "https://www.facebook.com", "description": "A platform for social networking and communication." },
  { "title": "Instagram", "url": "https://www.instagram.com", "description": "A photo and video-sharing social network." },
  { "title": "Twitter", "url": "https://www.twitter.com", "description": "A microblogging platform for short messages and updates." },
  { "title": "LinkedIn", "url": "https://www.linkedin.com", "description": "A professional networking platform for job seekers and businesses." },
  { "title": "Reddit", "url": "https://www.reddit.com", "description": "A forum with discussions on various topics." },
  { "title": "YouTube", "url": "https://www.youtube.com", "description": "A video-sharing platform with millions of videos." },
  { "title": "TikTok", "url": "https://www.tiktok.com", "description": "A platform for short-form video content." },
  { "title": "Netflix", "url": "https://www.netflix.com", "description": "A streaming service offering movies and TV shows." },
  { "title": "Amazon", "url": "https://www.amazon.com", "description": "Online shopping for books, electronics, and more." },
  { "title": "eBay", "url": "https://www.ebay.com", "description": "An online marketplace for buying and selling products." },
  { "title": "Tesla", "url": "https://www.tesla.com", "description": "Electric vehicles and sustainable energy solutions." },
  { "title": "Spotify", "url": "https://www.spotify.com", "description": "Music streaming service with millions of songs." },
  { "title": "Airbnb", "url": "https://www.airbnb.com", "description": "Find vacation rentals and experiences worldwide." },
  { "title": "Uber", "url": "https://www.uber.com", "description": "Ride-hailing and food delivery service worldwide." },
  { "title": "Pinterest", "url": "https://www.pinterest.com", "description": "A platform to discover and save creative ideas." },
  { "title": "BBC News", "url": "https://www.bbc.com/news", "description": "A global news organization providing the latest news." },
  { "title": "CNN", "url": "https://www.cnn.com", "description": "A major news network covering international affairs." },
  { "title": "Forbes", "url": "https://www.forbes.com", "description": "A business magazine covering finance and entrepreneurship." },
  { "title": "Bloomberg", "url": "https://www.bloomberg.com", "description": "Global business and market news." },
  { "title": "National Geographic", "url": "https://www.nationalgeographic.com", "description": "A magazine covering science, exploration, and nature." },
  { "title": "NASA", "url": "https://www.nasa.gov", "description": "The official site for the U.S. space agency." },
  { "title": "The New York Times", "url": "https://www.nytimes.com", "description": "Leading newspaper covering news and current events." },
  { "title": "The Guardian", "url": "https://www.theguardian.com", "description": "British newspaper offering global news coverage." },
  { "title": "Wikipedia", "url": "https://www.wikipedia.org", "description": "A free online encyclopedia with millions of articles." },
  { "title": "Quora", "url": "https://www.quora.com", "description": "A platform for asking and answering questions." },
  { "title": "Coursera", "url": "https://www.coursera.org", "description": "Online courses from top universities and companies." },
  { "title": "Khan Academy", "url": "https://www.khanacademy.org", "description": "Free online education platform for students of all ages." },
  { "title": "edX", "url": "https://www.edx.org", "description": "Massive open online courses from global institutions." },
  { "title": "Udemy", "url": "https://www.udemy.com", "description": "An online learning marketplace with courses on various topics." },
  { "title": "Twitch", "url": "https://www.twitch.tv", "description": "Live streaming platform for gamers and creators." },
  { "title": "SoundCloud", "url": "https://www.soundcloud.com", "description": "A platform for independent music artists to share their work." },
  { "title": "DeviantArt", "url": "https://www.deviantart.com", "description": "A platform for artists to showcase and sell artwork." },
  { "title": "Kickstarter", "url": "https://www.kickstarter.com", "description": "A crowdfunding platform for creative projects." },
  { "title": "GoFundMe", "url": "https://www.gofundme.com", "description": "A platform for personal fundraising campaigns." },
  { "title": "Walmart", "url": "https://www.walmart.com", "description": "Retail giant offering groceries, electronics, and more." },
  { "title": "Best Buy", "url": "https://www.bestbuy.com", "description": "Electronics retailer for gadgets, appliances, and more." },
  { "title": "Shopify", "url": "https://www.shopify.com", "description": "E-commerce platform for building online stores." },
  { "title": "Slack", "url": "https://www.slack.com", "description": "A communication and collaboration platform for teams." },
  { "title": "Zoom", "url": "https://www.zoom.us", "description": "A video conferencing platform for online meetings." },
  { "title": "Discord", "url": "https://www.discord.com", "description": "A communication platform for voice, video, and text chat." },
  { "title": "Trello", "url": "https://www.trello.com", "description": "A project management tool for teams and businesses." },
  { "title": "Canva", "url": "https://www.canva.com", "description": "An online graphic design tool for presentations, posters, and social media." },
  { "title": "Dropbox", "url": "https://www.dropbox.com", "description": "A cloud storage service for file sharing and collaboration." },
  { "title": "Grammarly", "url": "https://www.grammarly.com", "description": "A writing assistant that helps with grammar and style." },
  { "title": "Fiverr", "url": "https://www.fiverr.com", "description": "A freelance marketplace for digital services." },
  { "title": "Medium", "url": "https://www.medium.com", "description": "A blogging and publishing platform." },
  { "title": "Hulu", "url": "https://www.hulu.com", "description": "A streaming service offering TV shows, movies, and originals." },
  { "title": "PayPal", "url": "https://www.paypal.com", "description": "A secure online payment and money transfer service." },
  { "title": "Stripe", "url": "https://www.stripe.com", "description": "An online payment processing platform for businesses." },
  { "title": "Notion", "url": "https://www.notion.so", "description": "An all-in-one workspace for notes, tasks, and collaboration." },
  { "title": "Zapier", "url": "https://www.zapier.com", "description": "A tool that connects different apps to automate workflows." },
  { "title": "Gmail", "url": "https://www.gmail.com", "description": "Google's email service for personal and business use." },
  { "title": "Yahoo Mail", "url": "https://mail.yahoo.com", "description": "Yahoo's email service with a classic inbox experience." },
  { "title": "ProtonMail", "url": "https://www.protonmail.com", "description": "A secure and encrypted email service focused on privacy." },
  { "title": "Evernote", "url": "https://www.evernote.com", "description": "A note-taking app with powerful organizational features." },
  { "title": "Bitbucket", "url": "https://www.bitbucket.org", "description": "A Git-based source code repository for teams." },
  { "title": "Docker", "url": "https://www.docker.com", "description": "A containerization platform for developers and IT teams." },
  { "title": "Asana", "url": "https://www.asana.com", "description": "A task and project management tool for businesses." },
  { "title": "WeTransfer", "url": "https://www.wetransfer.com", "description": "A simple file-sharing service for large files." },
  { "title": "Kickstarter", "url": "https://www.kickstarter.com", "description": "A crowdfunding platform for creative projects." },
  { "title": "GoFundMe", "url": "https://www.gofundme.com", "description": "A platform for personal and nonprofit fundraising campaigns." },
  { "title": "Lynda", "url": "https://www.lynda.com", "description": "An online learning platform with professional courses." },
  { "title": "Skillshare", "url": "https://www.skillshare.com", "description": "A learning community offering creative and business skills." },
  { "title": "LastPass", "url": "https://www.lastpass.com", "description": "A password manager for secure storage and autofill." },
  { "title": "1Password", "url": "https://www.1password.com", "description": "A password management and security tool." },
  { "title": "Weebly", "url": "https://www.weebly.com", "description": "A website builder for businesses and personal sites." },
  { "title": "Wix", "url": "https://www.wix.com", "description": "A drag-and-drop website builder with customizable templates." },
  { "title": "Squarespace", "url": "https://www.squarespace.com", "description": "A platform for building modern websites and online stores." },
  { "title": "WordPress", "url": "https://www.wordpress.com", "description": "A blogging and website creation tool." },
  { "title": "Joomla", "url": "https://www.joomla.org", "description": "An open-source content management system for websites." },
  { "title": "Shopify", "url": "https://www.shopify.com", "description": "An e-commerce platform for building online stores." },
  { "title": "Magento", "url": "https://www.magento.com", "description": "A powerful e-commerce platform for online businesses." },
  { "title": "BigCommerce", "url": "https://www.bigcommerce.com", "description": "An e-commerce platform for scaling online stores." },
  { "title": "AliExpress", "url": "https://www.aliexpress.com", "description": "A marketplace for affordable products from China." },
  { "title": "Zillow", "url": "https://www.zillow.com", "description": "A real estate marketplace for buying, selling, and renting homes." },
  { "title": "Indeed", "url": "https://www.indeed.com", "description": "A job search engine with millions of listings." },
  { "title": "Glassdoor", "url": "https://www.glassdoor.com", "description": "Company reviews, salaries, and job listings." },
  { "title": "Monster", "url": "https://www.monster.com", "description": "A job search platform with career resources." },
  { "title": "The Weather Channel", "url": "https://weather.com", "description": "Real-time weather forecasts and climate news." },
  { "title": "AccuWeather", "url": "https://www.accuweather.com", "description": "Accurate weather updates and forecasts." },
  { "title": "National Geographic", "url": "https://www.nationalgeographic.com", "description": "Exploration, science, and storytelling." },
  { "title": "Smithsonian Magazine", "url": "https://www.smithsonianmag.com", "description": "Science, history, and culture articles." },
  { "title": "ESPN", "url": "https://www.espn.com", "description": "Sports news, scores, and analysis." },
  { "title": "Fox Sports", "url": "https://www.foxsports.com", "description": "Latest updates on global sports events." },
  { "title": "NHL", "url": "https://www.nhl.com", "description": "Official website for National Hockey League news and scores." },
  { "title": "NBA", "url": "https://www.nba.com", "description": "Latest basketball news, scores, and highlights." },
  { "title": "MLB", "url": "https://www.mlb.com", "description": "Major League Baseball news and updates." },
  { "title": "Google", "url": "https://www.google.com", "description": "The world's most popular search engine." },
  { "title": "GitHub", "url": "https://www.github.com", "description": "A code-sharing platform for developers." },
  { "title": "Stack Overflow", "url": "https://stackoverflow.com", "description": "A Q&A site for programmers." },
  { "title": "Mozilla", "url": "https://www.mozilla.org", "description": "Creators of the Firefox web browser." },
  { "title": "Linux", "url": "https://www.linux.org", "description": "Open-source operating system information and downloads." },
  { "title": "OpenAI", "url": "https://www.openai.com", "description": "Artificial intelligence research and development." },
  { "title": "Adobe", "url": "https://www.adobe.com", "description": "Creative software for design and media." },
  { "title": "Microsoft", "url": "https://www.microsoft.com", "description": "Home of Windows, Office, and cloud services." },
  { "title": "Apple", "url": "https://www.apple.com", "description": "Official site for iPhones, MacBooks, and other Apple products." },
  { "title": "Intel", "url": "https://www.intel.com", "description": "Leading semiconductor and processor manufacturer." },
  { "title": "Facebook", "url": "https://www.facebook.com", "description": "A platform for social networking and communication." },
  { "title": "Instagram", "url": "https://www.instagram.com", "description": "A photo and video-sharing social network." },
  { "title": "Twitter", "url": "https://www.twitter.com", "description": "A microblogging platform for short messages and updates." },
  { "title": "LinkedIn", "url": "https://www.linkedin.com", "description": "A professional networking platform for job seekers and businesses." },
  { "title": "Reddit", "url": "https://www.reddit.com", "description": "A forum with discussions on various topics." },
  { "title": "YouTube", "url": "https://www.youtube.com", "description": "A video-sharing platform with millions of videos." },
  { "title": "TikTok", "url": "https://www.tiktok.com", "description": "A platform for short-form video content." },
  { "title": "Netflix", "url": "https://www.netflix.com", "description": "A streaming service offering movies and TV shows." },
  { "title": "Amazon", "url": "https://www.amazon.com", "description": "Online shopping for books, electronics, and more." },
  { "title": "eBay", "url": "https://www.ebay.com", "description": "An online marketplace for buying and selling products." },
  { "title": "Tesla", "url": "https://www.tesla.com", "description": "Electric vehicles and sustainable energy solutions." },
  { "title": "Spotify", "url": "https://www.spotify.com", "description": "Music streaming service with millions of songs." },
  { "title": "Airbnb", "url": "https://www.airbnb.com", "description": "Find vacation rentals and experiences worldwide." },
  { "title": "Uber", "url": "https://www.uber.com", "description": "Ride-hailing and food delivery service worldwide." },
  { "title": "Pinterest", "url": "https://www.pinterest.com", "description": "A platform to discover and save creative ideas." },
  { "title": "BBC News", "url": "https://www.bbc.com/news", "description": "A global news organization providing the latest news." },
  { "title": "CNN", "url": "https://www.cnn.com", "description": "A major news network covering international affairs." },
  { "title": "Forbes", "url": "https://www.forbes.com", "description": "A business magazine covering finance and entrepreneurship." },
  { "title": "Bloomberg", "url": "https://www.bloomberg.com", "description": "Global business and market news." },
  { "title": "National Geographic", "url": "https://www.nationalgeographic.com", "description": "A magazine covering science, exploration, and nature." },
  { "title": "NASA", "url": "https://www.nasa.gov", "description": "The official site for the U.S. space agency." },
  { "title": "The New York Times", "url": "https://www.nytimes.com", "description": "Leading newspaper covering news and current events." },
  { "title": "Wikipedia", "url": "https://www.wikipedia.org", "description": "A free online encyclopedia with millions of articles." },
  { "title": "Quora", "url": "https://www.quora.com", "description": "A platform for asking and answering questions." },
  { "title": "Coursera", "url": "https://www.coursera.org", "description": "Online courses from top universities and companies." },
  { "title": "Khan Academy", "url": "https://www.khanacademy.org", "description": "Free online education platform for students of all ages." },
  { "title": "edX", "url": "https://www.edx.org", "description": "Massive open online courses from global institutions." },
  { "title": "Udemy", "url": "https://www.udemy.com", "description": "An online learning marketplace with courses on various topics." },
  { "title": "Zoom", "url": "https://www.zoom.us", "description": "A video conferencing platform for online meetings." },
  { "title": "Discord", "url": "https://www.discord.com", "description": "A communication platform for voice, video, and text chat." },
  { "title": "Trello", "url": "https://www.trello.com", "description": "A project management tool for teams and businesses." },
  { "title": "Canva", "url": "https://www.canva.com", "description": "An online graphic design tool for presentations, posters, and social media." },
  { "title": "Dropbox", "url": "https://www.dropbox.com", "description": "A cloud storage service for file sharing and collaboration." },
  { "title": "Grammarly", "url": "https://www.grammarly.com", "description": "A writing assistant that helps with grammar and style." },
  { "title": "Fiverr", "url": "https://www.fiverr.com", "description": "A freelance marketplace for digital services." },
  { "title": "Medium", "url": "https://www.medium.com", "description": "A blogging and publishing platform." },
  { "title": "Hulu", "url": "https://www.hulu.com", "description": "A streaming service offering TV shows, movies, and originals." },
  { "title": "PayPal", "url": "https://www.paypal.com", "description": "A secure online payment and money transfer service." },
  { "title": "Stripe", "url": "https://www.stripe.com", "description": "An online payment processing platform for businesses." },
  { "title": "Notion", "url": "https://www.notion.so", "description": "An all-in-one workspace for notes, tasks, and collaboration." },
  { "title": "Zapier", "url": "https://www.zapier.com", "description": "A tool that connects different apps to automate workflows." },
  { "title": "Gmail", "url": "https://www.gmail.com", "description": "Google's email service for personal and business use." },
  { "title": "Yahoo Mail", "url": "https://mail.yahoo.com", "description": "Yahoo's email service with a classic inbox experience." },
  { "title": "ProtonMail", "url": "https://www.protonmail.com", "description": "A secure and encrypted email service focused on privacy." },
  { "title": "Evernote", "url": "https://www.evernote.com", "description": "A note-taking app with powerful organizational features." },
  { "title": "Bitbucket", "url": "https://www.bitbucket.org", "description": "A Git-based source code repository for teams." },
  { "title": "Docker", "url": "https://www.docker.com", "description": "A containerization platform for developers and IT teams." },
  { "title": "Asana", "url": "https://www.asana.com", "description": "A task and project management tool for businesses." },
  { "title": "WeTransfer", "url": "https://www.wetransfer.com", "description": "A simple file-sharing service for large files." },
  { "title": "Kickstarter", "url": "https://www.kickstarter.com", "description": "A crowdfunding platform for creative projects." },
  { "title": "GoFundMe", "url": "https://www.gofundme.com", "description": "A platform for personal and nonprofit fundraising campaigns." },
  { "title": "Lynda", "url": "https://www.lynda.com", "description": "An online learning platform with professional courses." },
  { "title": "Skillshare", "url": "https://www.skillshare.com", "description": "A learning community offering creative and business skills." },
  { "title": "LastPass", "url": "https://www.lastpass.com", "description": "A password manager for secure storage and autofill." },
  { "title": "1Password", "url": "https://www.1password.com", "description": "A password management and security tool." },
  { "title": "Weebly", "url": "https://www.weebly.com", "description": "A website builder for businesses and personal sites." },
  { "title": "Wix", "url": "https://www.wix.com", "description": "A drag-and-drop website builder with customizable templates." },
  { "title": "Squarespace", "url": "https://www.squarespace.com", "description": "A platform for building modern websites and online stores." },
  { "title": "WordPress", "url": "https://www.wordpress.com", "description": "A blogging and website creation tool." },
  { "title": "Joomla", "url": "https://www.joomla.org", "description": "An open-source content management system for websites." },
  { "title": "Shopify", "url": "https://www.shopify.com", "description": "An e-commerce platform for building online stores." },
  { "title": "Magento", "url": "https://www.magento.com", "description": "A powerful e-commerce platform for online businesses." },
  { "title": "BigCommerce", "url": "https://www.bigcommerce.com", "description": "An e-commerce platform for scaling online stores." },
  { "title": "AliExpress", "url": "https://www.aliexpress.com", "description": "A marketplace for affordable products from China." },
  { "title": "Zillow", "url": "https://www.zillow.com", "description": "A real estate marketplace for buying, selling, and renting homes." },
  { "title": "Indeed", "url": "https://www.indeed.com", "description": "A job search engine with millions of listings." },
  { "title": "Glassdoor", "url": "https://www.glassdoor.com", "description": "Company reviews, salaries, and job listings." },
  { "title": "Monster", "url": "https://www.monster.com", "description": "A job search platform with career resources." },
  { "title": "NASA", "url": "https://www.nasa.gov", "description": "Official website of the U.S. space agency." },
  { "title": "National Geographic", "url": "https://www.nationalgeographic.com", "description": "Exploration, science, and storytelling." },
  { "title": "Smithsonian Magazine", "url": "https://www.smithsonianmag.com", "description": "Science, history, and culture articles." },
  { "title": "BBC News", "url": "https://www.bbc.com/news", "description": "Breaking news, analysis, and reports from around the world." },
  { "title": "The Guardian", "url": "https://www.theguardian.com", "description": "Independent journalism covering world news and opinions." },
  { "title": "Reuters", "url": "https://www.reuters.com", "description": "Trusted source for business, financial, and world news." },
  { "title": "CNBC", "url": "https://www.cnbc.com", "description": "Global news and financial market updates." },
  { "title": "Bloomberg", "url": "https://www.bloomberg.com", "description": "Global business and market news." },
  { "title": "Forbes", "url": "https://www.forbes.com", "description": "Business magazine covering finance, investing, and innovation." },
  { "title": "Harvard Business Review", "url": "https://hbr.org", "description": "Insights on leadership, management, and strategy." },
  { "title": "MIT Technology Review", "url": "https://www.technologyreview.com", "description": "Covers emerging technologies and their impact." },
  { "title": "Science Daily", "url": "https://www.sciencedaily.com", "description": "Latest research news from science and technology fields." },
  { "title": "Space.com", "url": "https://www.space.com", "description": "Covers space exploration, astronomy, and technology." },
  { "title": "Live Science", "url": "https://www.livescience.com", "description": "Explores fascinating scientific discoveries and mysteries." },
  { "title": "Phys.org", "url": "https://www.phys.org", "description": "Latest science and technology research updates." },
  { "title": "The Verge", "url": "https://www.theverge.com", "description": "Covers the intersection of technology, science, and culture." },
  { "title": "Wired", "url": "https://www.wired.com", "description": "Technology and innovation news and trends." },
  { "title": "TechCrunch", "url": "https://www.techcrunch.com", "description": "Startup and technology industry news." },
  { "title": "CNET", "url": "https://www.cnet.com", "description": "Gadget reviews, software news, and tech trends." },
  { "title": "Gizmodo", "url": "https://www.gizmodo.com", "description": "Technology and science news with analysis." },
  { "title": "Ars Technica", "url": "https://www.arstechnica.com", "description": "Technology and policy news, with in-depth analysis." },
  { "title": "PCMag", "url": "https://www.pcmag.com", "description": "Product reviews, news, and guides for technology consumers." },
  { "title": "ZDNet", "url": "https://www.zdnet.com", "description": "Business technology news and IT insights." },
  { "title": "MacRumors", "url": "https://www.macrumors.com", "description": "Apple news, rumors, and product discussions." },
  { "title": "Android Authority", "url": "https://www.androidauthority.com", "description": "Android news, app reviews, and tech insights." },
  { "title": "9to5Mac", "url": "https://www.9to5mac.com", "description": "Latest Apple news, leaks, and updates." },
  { "title": "Bleeping Computer", "url": "https://www.bleepingcomputer.com", "description": "Cybersecurity news and IT troubleshooting guides." },
  { "title": "Krebs on Security", "url": "https://krebsonsecurity.com", "description": "In-depth reporting on cybersecurity threats and issues." },
  { "title": "Have I Been Pwned", "url": "https://haveibeenpwned.com", "description": "Check if your email or data has been compromised." },
  { "title": "Dark Reading", "url": "https://www.darkreading.com", "description": "Cybersecurity news and expert insights." },
  { "title": "TorrentFreak", "url": "https://www.torrentfreak.com", "description": "Covers digital rights, privacy, and file-sharing news." },
  { "title": "The Pirate Bay", "url": "https://www.thepiratebay.org", "description": "A well-known torrent index for sharing files." },
  { "title": "Kickass Torrents", "url": "https://kickasstorrents.to", "description": "Peer-to-peer file-sharing search engine." },
  { "title": "SoundCloud", "url": "https://www.soundcloud.com", "description": "A platform for independent artists to share music." },
  { "title": "Bandcamp", "url": "https://www.bandcamp.com", "description": "A platform for artists to sell music and merchandise." },
  { "title": "Mixcloud", "url": "https://www.mixcloud.com", "description": "A streaming platform for DJs and radio shows." },
  { "title": "Tidal", "url": "https://www.tidal.com", "description": "High-fidelity music streaming and exclusive content." },
  { "title": "Deezer", "url": "https://www.deezer.com", "description": "A global music streaming service." },
  { "title": "Pandora", "url": "https://www.pandora.com", "description": "Personalized internet radio and music streaming." },
  { "title": "Shazam", "url": "https://www.shazam.com", "description": "Music recognition and discovery app." },
  { "title": "TuneIn", "url": "https://www.tunein.com", "description": "Live radio, music, and podcast streaming." },
  { "title": "Audible", "url": "https://www.audible.com", "description": "Audiobook streaming and downloads." },
  { "title": "LibriVox", "url": "https://www.librivox.org", "description": "Free public domain audiobooks." },
  { "title": "Project Gutenberg", "url": "https://www.gutenberg.org", "description": "A library of free eBooks, including classics." },
  { "title": "NASA", "url": "https://www.nasa.gov/missioncontrol/astronomy/235gdhh/", "description": "Official website of the U.S. space agency." },
  { "title": "National Geographic", "url": "https://www.nationalgeographic.com/expeditions/wildlife/98abc34/", "description": "Exploration, science, and storytelling." },
  { "title": "Smithsonian Magazine", "url": "https://www.smithsonianmag.com/history/artifacts/387dnsk/", "description": "Science, history, and culture articles." },
  { "title": "BBC News", "url": "https://www.bbc.com/news/world/europe/48hsdke/", "description": "Breaking news, analysis, and reports from around the world." },
  { "title": "The Guardian", "url": "https://www.theguardian.com/environment/climatechange/2987gfhd/", "description": "Independent journalism covering world news and opinions." },
  { "title": "Reuters", "url": "https://www.reuters.com/markets/stocks/98udjhsa/", "description": "Trusted source for business, financial, and world news." },
  { "title": "CNBC", "url": "https://www.cnbc.com/finance/realestate/83jdhsa9/", "description": "Global news and financial market updates." },
  { "title": "Bloomberg", "url": "https://www.bloomberg.com/technology/cybersecurity/234jdsla/", "description": "Global business and market news." },
  { "title": "Forbes", "url": "https://www.forbes.com/entrepreneurs/startups/92sdhja2/", "description": "Business magazine covering finance, investing, and innovation." },
  { "title": "Harvard Business Review", "url": "https://hbr.org/leadership/casestudies/45kdhsa7/", "description": "Insights on leadership, management, and strategy." },
  { "title": "MIT Technology Review", "url": "https://www.technologyreview.com/ai/future/562jshd8/", "description": "Covers emerging technologies and their impact." },
  { "title": "Science Daily", "url": "https://www.sciencedaily.com/news/health/biotech/23jdhsak/", "description": "Latest research news from science and technology fields." },
  { "title": "Space.com", "url": "https://www.space.com/astronomy/moonlanding/78gdhsa/", "description": "Covers space exploration, astronomy, and technology." },
  { "title": "Live Science", "url": "https://www.livescience.com/earth/climatechange/298hdjsk/", "description": "Explores fascinating scientific discoveries and mysteries." },
  { "title": "Phys.org", "url": "https://www.phys.org/news/materialscience/763jdhsa/", "description": "Latest science and technology research updates." },
  { "title": "The Verge", "url": "https://www.theverge.com/gaming/reviews/34hjdksa/", "description": "Covers the intersection of technology, science, and culture." },
  { "title": "Wired", "url": "https://www.wired.com/gadgets/innovation/283jsdha/", "description": "Technology and innovation news and trends." },
  { "title": "TechCrunch", "url": "https://www.techcrunch.com/startups/funding/83jdksha/", "description": "Startup and technology industry news." },
  { "title": "CNET", "url": "https://www.cnet.com/reviews/laptops/gaming/98jdhska/", "description": "Gadget reviews, software news, and tech trends." },
  { "title": "Gizmodo", "url": "https://www.gizmodo.com/robotics/ai-integration/93jdhsak/", "description": "Technology and science news with analysis." },
  { "title": "Ars Technica", "url": "https://www.arstechnica.com/tech/policy/893jdhsa/", "description": "Technology and policy news, with in-depth analysis." },
  { "title": "PCMag", "url": "https://www.pcmag.com/software/security/82hdjskl/", "description": "Product reviews, news, and guides for technology consumers." },
  { "title": "ZDNet", "url": "https://www.zdnet.com/cloudcomputing/futuretrends/82jhdksa/", "description": "Business technology news and IT insights." },
  { "title": "MacRumors", "url": "https://www.macrumors.com/apple/iphone16/98jdhska/", "description": "Apple news, rumors, and product discussions." },
  { "title": "Android Authority", "url": "https://www.androidauthority.com/smartphones/cameracomparison/82jdhsak/", "description": "Android news, app reviews, and tech insights." },
  { "title": "9to5Mac", "url": "https://www.9to5mac.com/apple/macosnewupdate/98jdhska/", "description": "Latest Apple news, leaks, and updates." },
  { "title": "Bleeping Computer", "url": "https://www.bleepingcomputer.com/cybersecurity/malwarealerts/76jdhsak/", "description": "Cybersecurity news and IT troubleshooting guides." },
  { "title": "Krebs on Security", "url": "https://krebsonsecurity.com/hackers/reports/45jdhska/", "description": "In-depth reporting on cybersecurity threats and issues." },
  { "title": "Have I Been Pwned", "url": "https://haveibeenpwned.com/breaches/database/34jdhsa7/", "description": "Check if your email or data has been compromised." },
  { "title": "Dark Reading", "url": "https://www.darkreading.com/networksecurity/threatanalysis/23jhdksa/", "description": "Cybersecurity news and expert insights." },
  { "title": "SoundCloud", "url": "https://www.soundcloud.com/artists/featured/98jdhska/", "description": "A platform for independent artists to share music." },
  { "title": "Tidal", "url": "https://www.tidal.com/music/newreleases/23jdhsak/", "description": "High-fidelity music streaming and exclusive content." },
  { "title": "Deezer", "url": "https://www.deezer.com/playlist/topcharts/45jdhska/", "description": "A global music streaming service." },
  { "title": "Pandora", "url": "https://www.pandora.com/radio/stations/92jhdksa/", "description": "Personalized internet radio and music streaming." },
  { "title": "Audible", "url": "https://www.audible.com/audiobooks/newreleases/83jdhska/", "description": "Audiobook streaming and downloads." },
  { "title": "LibriVox", "url": "https://www.librivox.org/audiobooks/classics/76jdhsak/", "description": "Free public domain audiobooks." },
  { "title": "Project Gutenberg", "url": "https://www.gutenberg.org/ebooks/featured/45jdhska/", "description": "A library of free eBooks, including classics." },
  { "title": "National Library", "url": "https://www.nationallibrary.gov/resources/ebooks/39kdhja/", "description": "A collection of historical and modern books." },
  { "title": "TechRadar", "url": "https://www.techradar.com/gadgets/innovation/63jdksla/", "description": "Latest trends in consumer electronics and software." },
  { "title": "Investopedia", "url": "https://www.investopedia.com/finance/stockmarket/29dhsakl/", "description": "Comprehensive financial education and market insights." },
  { "title": "GameSpot", "url": "https://www.gamespot.com/reviews/latest/93jdhska/", "description": "Video game reviews, news, and previews." },
  { "title": "IGN", "url": "https://www.ign.com/movies/upcoming/48jdhsak/", "description": "Entertainment news, gaming reviews, and pop culture updates." },
  { "title": "TripAdvisor", "url": "https://www.tripadvisor.com/destinations/toprated/78jdhsak/", "description": "Reviews and recommendations for hotels and travel spots." },
  { "title": "Lonely Planet", "url": "https://www.lonelyplanet.com/guides/besttrips/28jdhsak/", "description": "Travel tips and destination guides worldwide." },
  { "title": "Healthline", "url": "https://www.healthline.com/nutrition/fitnessguides/38jdhska/", "description": "Health and wellness tips backed by research." },
  { "title": "Mayo Clinic", "url": "https://www.mayoclinic.org/diseases/diagnosis/84jdhska/", "description": "Reliable medical information and expert advice." },
  { "title": "MedlinePlus", "url": "https://www.medlineplus.gov/conditions/treatments/92jdhsak/", "description": "Medical encyclopedia and health resources." },
  { "title": "The Spruce", "url": "https://www.thespruce.com/home/interiordesign/38jdhska/", "description": "Home improvement, decor, and gardening tips." },
  { "title": "House Beautiful", "url": "https://www.housebeautiful.com/design/ideas/83jdhsak/", "description": "Interior design inspiration and home decor trends." },
  { "title": "Food Network", "url": "https://www.foodnetwork.com/recipes/newdishes/28jdhsak/", "description": "Cooking tips, recipes, and food culture." },
  { "title": "AllRecipes", "url": "https://www.allrecipes.com/toprated/meals/84jdhsak/", "description": "A collection of user-submitted recipes from around the world." },
  { "title": "Epicurious", "url": "https://www.epicurious.com/cookingguides/tips/76jdhsak/", "description": "Expert cooking tips and food trends." },
  { "title": "Yelp", "url": "https://www.yelp.com/bestbusinesses/cities/94jdhsak/", "description": "User-generated reviews of businesses and restaurants." },
  { "title": "Rotten Tomatoes", "url": "https://www.rottentomatoes.com/movies/toprated/29jdhsak/", "description": "Movie ratings, reviews, and entertainment news." },
  { "title": "Metacritic", "url": "https://www.metacritic.com/games/latestreviews/73jdhsak/", "description": "Critic and user reviews for movies, games, and music." },
  { "title": "Goodreads", "url": "https://www.goodreads.com/books/bestofyear/27jdhsak/", "description": "Book recommendations and reader reviews." },
  { "title": "Barnes & Noble", "url": "https://www.barnesandnoble.com/bookstore/bestsellers/48jdhsak/", "description": "A wide selection of books, magazines, and more." },
  { "title": "TED Talks", "url": "https://www.ted.com/talks/mostpopular/83jdhsak/", "description": "Inspirational talks on various topics." },
  { "title": "Coursera", "url": "https://www.coursera.org/courses/trending/39jdhsak/", "description": "Online learning from top universities and experts." },
  { "title": "Udacity", "url": "https://www.udacity.com/nanodegree/featured/24jdhsak/", "description": "Tech courses and career-advancing programs." },
  { "title": "Skillshare", "url": "https://www.skillshare.com/classes/creativelearning/98jdhsak/", "description": "Online creative and business skill courses." },
  { "title": "GitHub", "url": "https://www.github.com/repos/trending/62jdhsak/", "description": "A platform for developers to share and collaborate on code." },
  { "title": "Bitbucket", "url": "https://www.bitbucket.org/teams/openprojects/73jdhsak/", "description": "Git-based source code repository for teams." },
  { "title": "Docker Hub", "url": "https://hub.docker.com/images/popular/83jdhsak/", "description": "Containerized application images and resources." },
  { "title": "Slack", "url": "https://www.slack.com/workspaces/teamcollab/29jdhsak/", "description": "A messaging platform for businesses and teams." },
  { "title": "Zoom", "url": "https://www.zoom.us/meetings/newfeatures/83jdhsak/", "description": "A video conferencing platform for online meetings." },
  { "title": "Trello", "url": "https://www.trello.com/boards/productivity/62jdhsak/", "description": "A project management tool for teams." },
  { "title": "Notion", "url": "https://www.notion.so/workspaces/teamprojects/98jdhsak/", "description": "An all-in-one workspace for notes and collaboration." },
  { "title": "National Library", "url": "https://www.nationallibrary.gov/resources/ebooks/39kdhja/", "description": "A collection of historical and modern books." },
  { "title": "TechRadar", "url": "https://www.techradar.com/gadgets/innovation/63jdksla/", "description": "Latest trends in consumer electronics and software." },
  { "title": "Investopedia", "url": "https://www.investopedia.com/finance/stockmarket/29dhsakl/", "description": "Comprehensive financial education and market insights." },
  { "title": "GameSpot", "url": "https://www.gamespot.com/reviews/latest/93jdhska/", "description": "Video game reviews, news, and previews." },
  { "title": "IGN", "url": "https://www.ign.com/movies/upcoming/48jdhsak/", "description": "Entertainment news, gaming reviews, and pop culture updates." },
  { "title": "TripAdvisor", "url": "https://www.tripadvisor.com/destinations/toprated/78jdhsak/", "description": "Reviews and recommendations for hotels and travel spots." },
  { "title": "Lonely Planet", "url": "https://www.lonelyplanet.com/guides/besttrips/28jdhsak/", "description": "Travel tips and destination guides worldwide." },
  { "title": "Healthline", "url": "https://www.healthline.com/nutrition/fitnessguides/38jdhska/", "description": "Health and wellness tips backed by research." },
  { "title": "Mayo Clinic", "url": "https://www.mayoclinic.org/diseases/diagnosis/84jdhska/", "description": "Reliable medical information and expert advice." },
  { "title": "MedlinePlus", "url": "https://www.medlineplus.gov/conditions/treatments/92jdhsak/", "description": "Medical encyclopedia and health resources." },
  { "title": "The Spruce", "url": "https://www.thespruce.com/home/interiordesign/38jdhska/", "description": "Home improvement, decor, and gardening tips." },
  { "title": "House Beautiful", "url": "https://www.housebeautiful.com/design/ideas/83jdhsak/", "description": "Interior design inspiration and home decor trends." },
  { "title": "Food Network", "url": "https://www.foodnetwork.com/recipes/newdishes/28jdhsak/", "description": "Cooking tips, recipes, and food culture." },
  { "title": "AllRecipes", "url": "https://www.allrecipes.com/toprated/meals/84jdhsak/", "description": "A collection of user-submitted recipes from around the world." },
  { "title": "Epicurious", "url": "https://www.epicurious.com/cookingguides/tips/76jdhsak/", "description": "Expert cooking tips and food trends." },
  { "title": "Yelp", "url": "https://www.yelp.com/bestbusinesses/cities/94jdhsak/", "description": "User-generated reviews of businesses and restaurants." },
  { "title": "Rotten Tomatoes", "url": "https://www.rottentomatoes.com/movies/toprated/29jdhsak/", "description": "Movie ratings, reviews, and entertainment news." },
  { "title": "Metacritic", "url": "https://www.metacritic.com/games/latestreviews/73jdhsak/", "description": "Critic and user reviews for movies, games, and music." },
  { "title": "Goodreads", "url": "https://www.goodreads.com/books/bestofyear/27jdhsak/", "description": "Book recommendations and reader reviews." },
  { "title": "Barnes & Noble", "url": "https://www.barnesandnoble.com/bookstore/bestsellers/48jdhsak/", "description": "A wide selection of books, magazines, and more." },
  { "title": "TED Talks", "url": "https://www.ted.com/talks/mostpopular/83jdhsak/", "description": "Inspirational talks on various topics." },
  { "title": "Coursera", "url": "https://www.coursera.org/courses/trending/39jdhsak/", "description": "Online learning from top universities and experts." },
  { "title": "Udacity", "url": "https://www.udacity.com/nanodegree/featured/24jdhsak/", "description": "Tech courses and career-advancing programs." },
  { "title": "Skillshare", "url": "https://www.skillshare.com/classes/creativelearning/98jdhsak/", "description": "Online creative and business skill courses." },
  { "title": "GitHub", "url": "https://www.github.com/repos/trending/62jdhsak/", "description": "A platform for developers to share and collaborate on code." },
  { "title": "Bitbucket", "url": "https://www.bitbucket.org/teams/openprojects/73jdhsak/", "description": "Git-based source code repository for teams." },
  { "title": "Docker Hub", "url": "https://hub.docker.com/images/popular/83jdhsak/", "description": "Containerized application images and resources." },
  { "title": "Slack", "url": "https://www.slack.com/workspaces/teamcollab/29jdhsak/", "description": "A messaging platform for businesses and teams." },
  { "title": "Zoom", "url": "https://www.zoom.us/meetings/newfeatures/83jdhsak/", "description": "A video conferencing platform for online meetings." },
  { "title": "Trello", "url": "https://www.trello.com/boards/productivity/62jdhsak/", "description": "A project management tool for teams." },
  { "title": "Notion", "url": "https://www.notion.so/workspaces/teamprojects/98jdhsak/", "description": "An all-in-one workspace for notes and collaboration." },
  { "title": "AI Research Lab", "url": "https://www.airesearch.com/projects/deeplearning/12abc34/", "description": "Cutting-edge research on artificial intelligence and deep learning." },
  { "title": "Space Exploration News", "url": "https://www.spaceexplorers.org/news/missions/56xyz78/", "description": "Latest updates on space missions and discoveries." },
  { "title": "Global Stock Market", "url": "https://www.globalstocks.com/markets/trends/90efg12/", "description": "Real-time stock market trends and financial insights." },
  { "title": "Gourmet Recipes", "url": "https://www.foodieheaven.com/recipes/gourmet/34hij56/", "description": "Delicious and exotic recipes from around the world." },
  { "title": "Cybersecurity Watch", "url": "https://www.cybersecure.com/reports/threats/78klm90/", "description": "Stay updated with the latest cybersecurity threats and solutions." },
  { "title": "Eco-Friendly Living", "url": "https://www.greenworld.com/lifestyle/tips/23nop45/", "description": "Sustainable living tips and eco-friendly practices." },
  { "title": "Fitness & Wellness", "url": "https://www.healthboost.com/guides/fitness/67qrs89/", "description": "Expert advice on fitness, nutrition, and overall well-being." },
  { "title": "Travel Diaries", "url": "https://www.adventurelogs.com/stories/destinations/01tuv23/", "description": "Inspiring travel stories and top destinations to explore." },
  { "title": "Classic Literature Archive", "url": "https://www.bookworm.com/classics/novels/45wxy67/", "description": "A collection of timeless literary masterpieces." },
  { "title": "Gadget Reviews", "url": "https://www.techinsights.com/reviews/latest/89zab12/", "description": "Honest reviews on the newest tech gadgets and devices." },
  { "title": "Coding Tutorials", "url": "https://www.devhub.com/learn/programming/34cde56/", "description": "Free coding tutorials and programming guides." },
  { "title": "Startup Insights", "url": "https://www.bizgrowth.com/startups/funding/78fgh90/", "description": "Guides and tips for entrepreneurs launching a startup." },
  { "title": "Photography Tips", "url": "https://www.captureperfect.com/techniques/pro/23ijk45/", "description": "Professional photography techniques and equipment reviews." },
  { "title": "Mindfulness & Meditation", "url": "https://www.innerpeace.com/guides/meditation/67lmn89/", "description": "Practical tips for mindfulness and stress relief." },
  { "title": "Auto Trends", "url": "https://www.carworld.com/news/2024models/01opq23/", "description": "Latest automotive industry trends and vehicle reviews." },
  { "title": "DIY Home Projects", "url": "https://www.homemakers.com/diy/crafts/45rst67/", "description": "Creative DIY projects to enhance your home." },
  { "title": "Music Trends", "url": "https://www.melodicbeats.com/charts/top100/89uvw12/", "description": "Discover trending music across different genres." },
  { "title": "Gaming Strategies", "url": "https://www.gamerzone.com/guides/strategy/34xyz56/", "description": "Pro tips and walkthroughs for the latest video games." },
  { "title": "Science Discoveries", "url": "https://www.scientifica.com/breakthroughs/latest/78abc90/", "description": "Recent discoveries and advancements in science." },
  { "title": "Pet Care Tips", "url": "https://www.petlovers.com/health/guides/23def45/", "description": "Advice on keeping your pets happy and healthy." },
  { "title": "Cryptocurrency Insights", "url": "https://www.cryptoworld.com/market/updates/67ghi89/", "description": "Daily updates on Bitcoin, Ethereum, and crypto trends." },
  { "title": "Interior Design Ideas", "url": "https://www.decorhub.com/trends/2024styles/01jkl23/", "description": "Modern interior design ideas and decor inspirations." },
  { "title": "Astronomy Guides", "url": "https://www.cosmoswatch.com/stargazing/basics/45mno67/", "description": "Guides on stargazing and understanding the universe." },
  { "title": "Mental Health Awareness", "url": "https://www.mindstrong.com/wellness/tips/89pqr12/", "description": "Resources and guidance for mental well-being." },
  { "title": "Remote Work Productivity", "url": "https://www.digitalnomads.com/work/tools/34stu56/", "description": "Best tools and strategies for working remotely." },
  { "title": "AI Ethics", "url": "https://www.futuretech.com/ai/responsible/78vwx90/", "description": "Discussions on AI ethics and its impact on society." },
  { "title": "Luxury Watches", "url": "https://www.timelessstyle.com/watches/collectors/23yz12/", "description": "A guide to luxury watches and rare collections." },
  { "title": "Healthy Recipes", "url": "https://www.nutritionhub.com/recipes/healthymeals/67abc45/", "description": "Nutritious recipes for a balanced lifestyle." },
  { "title": "Virtual Reality News", "url": "https://www.vrworld.com/news/latest/01def23/", "description": "Latest updates on VR technology and applications." },
  { "title": "Bike Touring", "url": "https://www.cyclingadventures.com/routes/toptrails/45ghi67/", "description": "Best cycling routes and gear recommendations." },
  { "title": "E-Sports Updates", "url": "https://www.esportsarena.com/tournaments/2024champions/89jkl12/", "description": "Upcoming e-sports events and player rankings." },
  { "title": "Fashion Week Highlights", "url": "https://www.stylewatch.com/events/runway/34mno56/", "description": "Top moments from global fashion weeks." },
  { "title": "Public Speaking Tips", "url": "https://www.speakconfidently.com/skills/mastery/78pqr90/", "description": "Techniques to become a powerful public speaker." },
  { "title": "Eco-Friendly Travel", "url": "https://www.greentravel.com/tours/sustainable/23stu45/", "description": "Sustainable travel tips and eco-conscious destinations." },
  { "title": "Personal Finance", "url": "https://www.smartmoney.com/invest/saving/67vwx89/", "description": "Smart ways to manage your finances and investments." },
  { "title": "Space Tech Innovations", "url": "https://www.spacetech.com/engineering/latest/01yz23/", "description": "The latest breakthroughs in space exploration technology." }

];

// Adding more links dynamically
for (let i = 1; i <= 980; i++) {
  searchData.push({
    title: `Sample Site ${i}`,
    url: `https://www.samplesite${i}.com`,
    description: `This is a sample website number ${i}.`
  });
}

// Serve index.html as the homepage
app.get("/", (req, res) => {
  res.sendFile(path.join(__dirname, "public", "index.html"));
});

// Search endpoint (matches title, description, and URL, even with single letters or partial words)
app.get("/search", (req, res) => {
  const query = req.query.q ? req.query.q.toLowerCase().trim() : "";
  if (!query) return res.json([]);

  const results = searchData.filter(item => 
    item.title.toLowerCase().includes(query) ||
    item.description.toLowerCase().includes(query) ||
    item.url.toLowerCase().includes(query) // Now also matches URLs
  );

  res.json(results);
});

app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
